### ISSUE TITLE
Ported to SPI

### ISSUE THREAD

**Issue by stefandz** [SodaqMoja/Sodaq_LIS3DE#2]
Hi

Just to let you know I took this (actually the ctjet fork) and ported it to work with SPI. Structure is a little different - take a look [here](https://github.com/stefandz/LIS3DE_SPI). I've updated readme.md to reflect my changes, hopefully in line with your requirements.

Please let me know if there are any issues with the way I have modified and reshared your code.

Thanks!

Stefan

**Comment by SodaqMoja** [comment]
It's OK with us. We're happy that it was useful to you.
Thanks for letting us know.

BTW. I saw you dropped the underscore from the class members. We have that convention to avoid possible mixups with function parameters or other variables. Your code is probably correct, but I want to mention it anyway.

**Comment by stefandz** [comment]
All sounds good to me! I totally understand motivation for underscoring class members - just not my style! I prefer to enforce through `this->` although I appreciate that leaves more space for more bughunting. Maybe you'll find the keywords.txt and example code useful for your lib - feel free to pull them back across if you like.
